using System.Text.Json.Serialization;

namespace CurrencyConverter.Models
{
    public class Valyuta
    {
        public string Id { get; set; }
        public string Mamlakat { get; set; }
        public string ValyutaNomi { get; set; }
        public string Kodi { get; set; }
    }

    public class KursModel
    {
        public string Kodi { get; set; }
        public float Qiymat { get; set; }
    }


    public class Rootobject
    {
        [JsonPropertyName("date")]
        public string date { get; set; }

        [JsonPropertyName("usd")]
        public UsdcData usd { get; set; }
    }   

    public class UsdcData
    {
        [JsonPropertyName("uzs")]
        public float uzs { get; set; }

        [JsonPropertyName("1inch")]
        public float OneInch { get; set; }
        public float aave { get; set; }
        public float ada { get; set; }
        public float aed { get; set; }
        public float afn { get; set; }
        public float agix { get; set; }
        public float akt { get; set; }
        public float algo { get; set; }
        public float all { get; set; }
        public float amd { get; set; }
        public float amp { get; set; }
        public float ang { get; set; }
        public float aoa { get; set; }
        public float ape { get; set; }
        public float apt { get; set; }
        public float ar { get; set; }
        public float arb { get; set; }
        public float ars { get; set; }
        public float atom { get; set; }
        public float ats { get; set; }
        public float aud { get; set; }
        public float avax { get; set; }
        public float awg { get; set; }
        public float axs { get; set; }
        public float azm { get; set; }
        public float azn { get; set; }
        public float bake { get; set; }
        public float bam { get; set; }
        public float bat { get; set; }
        public float bbd { get; set; }
        public float bch { get; set; }
        public float bdt { get; set; }
        public float bef { get; set; }
        public float bgn { get; set; }
        public float bhd { get; set; }
        public float bif { get; set; }
        public float bmd { get; set; }
        public float bnb { get; set; }
        public float bnd { get; set; }
        public float bob { get; set; }
        public float brl { get; set; }
        public float bsd { get; set; }
        public float bsv { get; set; }
        public float bsw { get; set; }
        public float btc { get; set; }
        public float btg { get; set; }
        public float btn { get; set; }
        public float btt { get; set; }
        public float busd { get; set; }
        public float bwp { get; set; }
        public float byn { get; set; }
        public float byr { get; set; }
        public float bzd { get; set; }
        public float cad { get; set; }
        public float cake { get; set; }
        public float cdf { get; set; }
        public float celo { get; set; }
        public float cfx { get; set; }
        public float chf { get; set; }
        public float chz { get; set; }
        public float clp { get; set; }
        public float cnh { get; set; }
        public float cny { get; set; }
        public float comp { get; set; }
        public float cop { get; set; }
        public float crc { get; set; }
        public float cro { get; set; }
        public float crv { get; set; }
        public float cspr { get; set; }
        public float cuc { get; set; }
        public float cup { get; set; }
        public float cve { get; set; }
        public float cvx { get; set; }
        public float cyp { get; set; }
        public float czk { get; set; }
        public float dai { get; set; }
        public float dash { get; set; }
        public float dcr { get; set; }
        public float dem { get; set; }
        public float dfi { get; set; }
        public float djf { get; set; }
        public float dkk { get; set; }
        public float doge { get; set; }
        public float dop { get; set; }
        public float dot { get; set; }
        public float dydx { get; set; }
        public float dzd { get; set; }
        public float eek { get; set; }
        public float egld { get; set; }
        public float egp { get; set; }
        public float enj { get; set; }
        public float eos { get; set; }
        public float ern { get; set; }
        public float esp { get; set; }
        public float etb { get; set; }
        public float etc { get; set; }
        public float eth { get; set; }
        public float eur { get; set; }
        public float eurc { get; set; }
        public float fei { get; set; }
        public float fil { get; set; }
        public float fim { get; set; }
        public float fjd { get; set; }
        public float fkp { get; set; }
        public float flow { get; set; }
        public float flr { get; set; }
        public float frax { get; set; }
        public float frf { get; set; }
        public float ftt { get; set; }
        public float gala { get; set; }
        public float gbp { get; set; }
        public float gel { get; set; }
        public float ggp { get; set; }
        public float ghc { get; set; }
        public float ghs { get; set; }
        public float gip { get; set; }
        public float gmd { get; set; }
        public float gmx { get; set; }
        public float gnf { get; set; }
        public float gno { get; set; }
        public float grd { get; set; }
        public float grt { get; set; }
        public float gt { get; set; }
        public float gtq { get; set; }
        public float gusd { get; set; }
        public float gyd { get; set; }
        public float hbar { get; set; }
        public float hkd { get; set; }
        public float hnl { get; set; }
        public float hnt { get; set; }
        public float hot { get; set; }
        public float hrk { get; set; }
        public float ht { get; set; }
        public float htg { get; set; }
        public float huf { get; set; }
        public float icp { get; set; }
        public float idr { get; set; }
        public float iep { get; set; }
        public float ils { get; set; }
        public float imp { get; set; }
        public float imx { get; set; }
        public float inj { get; set; }
        public float inr { get; set; }
        public float iqd { get; set; }
        public float irr { get; set; }
        public float isk { get; set; }
        public float itl { get; set; }
        public float jep { get; set; }
        public float jmd { get; set; }
        public float jod { get; set; }
        public float jpy { get; set; }
        public float kas { get; set; }
        public float kava { get; set; }
        public float kcs { get; set; }
        public float kda { get; set; }
        public float kes { get; set; }
        public float kgs { get; set; }
        public float khr { get; set; }
        public float klay { get; set; }
        public float kmf { get; set; }
        public float knc { get; set; }
        public float kpw { get; set; }
        public float krw { get; set; }
        public float ksm { get; set; }
        public float kwd { get; set; }
        public float kyd { get; set; }
        public float kzt { get; set; }
        public float lak { get; set; }
        public float lbp { get; set; }
        public float ldo { get; set; }
        public float leo { get; set; }
        public float link { get; set; }
        public float lkr { get; set; }
        public float lrc { get; set; }
        public float lrd { get; set; }
        public float lsl { get; set; }
        public float ltc { get; set; }
        public float ltl { get; set; }
        public float luf { get; set; }
        public float luna { get; set; }
        public float lunc { get; set; }
        public float lvl { get; set; }
        public float lyd { get; set; }
        public float mad { get; set; }
        public float mana { get; set; }
        public float mbx { get; set; }
        public float mdl { get; set; }
        public float mga { get; set; }
        public float mgf { get; set; }
        public float mina { get; set; }
        public float mkd { get; set; }
        public float mkr { get; set; }
        public float mmk { get; set; }
        public float mnt { get; set; }
        public float mop { get; set; }
        public float mro { get; set; }
        public float mru { get; set; }
        public float mtl { get; set; }
        public float mur { get; set; }
        public float mvr { get; set; }
        public float mwk { get; set; }
        public float mxn { get; set; }
        public float mxv { get; set; }
        public float myr { get; set; }
        public float mzm { get; set; }
        public float mzn { get; set; }
        public float nad { get; set; }
        public float near { get; set; }
        public float neo { get; set; }
        public float nexo { get; set; }
        public float nft { get; set; }
        public float ngn { get; set; }
        public float nio { get; set; }
        public float nlg { get; set; }
        public float nok { get; set; }
        public float npr { get; set; }
        public float nzd { get; set; }
        public float okb { get; set; }
        public float omr { get; set; }
        public float one { get; set; }
        public float op { get; set; }
        public float ordi { get; set; }
        public float pab { get; set; }
        public float paxg { get; set; }
        public float pen { get; set; }
        public float pepe { get; set; }
        public float pgk { get; set; }
        public float php { get; set; }
        public float pi { get; set; }
        public float pkr { get; set; }
        public float pln { get; set; }
        public float pol { get; set; }
        public float pte { get; set; }
        public float pyg { get; set; }
        public float qar { get; set; }
        public float qnt { get; set; }
        public float qtum { get; set; }
        public float rol { get; set; }
        public float ron { get; set; }
        public float rpl { get; set; }
        public float rsd { get; set; }
        public float rub { get; set; }
        public float rune { get; set; }
        public float rvn { get; set; }
        public float rwf { get; set; }
        public float sand { get; set; }
        public float sar { get; set; }
        public float sbd { get; set; }
        public float scr { get; set; }
        public float sdd { get; set; }
        public float sdg { get; set; }
        public float sek { get; set; }
        public float sgd { get; set; }
        public float shib { get; set; }
        public float shp { get; set; }
        public float sit { get; set; }
        public float skk { get; set; }
        public float sle { get; set; }
        public float sll { get; set; }
        public float snx { get; set; }
        public float sol { get; set; }
        public float sos { get; set; }
        public float spl { get; set; }
        public float srd { get; set; }
        public float srg { get; set; }
        public float ssp { get; set; }
        public float std { get; set; }
        public float stn { get; set; }
        public float stx { get; set; }
        public float sui { get; set; }
        public float svc { get; set; }
        public float syp { get; set; }
        public float szl { get; set; }
        public float thb { get; set; }
        public float theta { get; set; }
        public float tjs { get; set; }
        public float tmm { get; set; }
        public float tmt { get; set; }
        public float tnd { get; set; }
        public float ton { get; set; }
        public float top { get; set; }
        public float trl { get; set; }
        public float trx { get; set; }
        [JsonPropertyName("try")]
        public float _try { get; set; }
        public float ttd { get; set; }
        public float tusd { get; set; }
        public float tvd { get; set; }
        public float twd { get; set; }
        public float twt { get; set; }
        public float tzs { get; set; }
        public float uah { get; set; }
        public float ugx { get; set; }
        public float uni { get; set; }
        public float usd { get; set; }
        public float usdc { get; set; }
        public float usdd { get; set; }
        public float usdp { get; set; }
        public float usdt { get; set; }
        public float uyu { get; set; }
        //public float uzs { get; set; }
        public float val { get; set; }
        public float veb { get; set; }
        public float ved { get; set; }
        public float vef { get; set; }
        public float ves { get; set; }
        public float vet { get; set; }
        public float vnd { get; set; }
        public float vuv { get; set; }
        public float waves { get; set; }
        public float wemix { get; set; }
        public float woo { get; set; }
        public float wst { get; set; }
        public float xaf { get; set; }
        public float xag { get; set; }
        public float xau { get; set; }
        public float xaut { get; set; }
        public float xbt { get; set; }
        public float xcd { get; set; }
        public float xcg { get; set; }
        public float xch { get; set; }
        public float xdc { get; set; }
        public float xdr { get; set; }
        public float xec { get; set; }
        public float xem { get; set; }
        public float xlm { get; set; }
        public float xmr { get; set; }
        public float xof { get; set; }
        public float xpd { get; set; }
        public float xpf { get; set; }
        public float xpt { get; set; }
        public float xrp { get; set; }
        public float xtz { get; set; }
        public float yer { get; set; }
        public float zar { get; set; }
        public float zec { get; set; }
        public float zil { get; set; }
        public float zmk { get; set; }
        public float zmw { get; set; }
        public float zwd { get; set; }
        public float zwg { get; set; }
        public float zwl { get; set; }
    }
}
